apiVersion: v1
kind: Secret
metadata:
  name: seip-assignment-1-secret
# used opaque because it's a random password
type: Opaque
data:
  # key encrypted with Base64
  API_SECRET_KEY: cGFzc3dvcmQyNTM4cHJvYmxlbQ==