apiVersion: v1
kind: Service
metadata:
  name: seip-assignment-1-service
spec:
  # service type
  type: ClusterIP
  selector:
    app: seip-assignment-1
  #map traffic
  ports:
    - port: 80
      targetPort: 3000